config/routes.rb
Rails.application.routes.draw do
  root to: 'users#show'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  post '/facebook-deletion', to: 'users#facebook_deletion'
  resources :users, only: [:show, :destroy] do
    resources :groups, except: [:edit, :update, :destroy]
    resources :activities, except: [:edit, :show, :update, :destroy]
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  validates_presence_of :name, :group_id, :time

  belongs_to :user
  belongs_to :group

  scope :not, ->(id) { where.not('group_id= ?', id) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :of, ->(this_user) { where('user_id= ?', this_user.id) }
  scope :ordered_by_most_recent, -> { order('created_at DESC') }
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates_uniqueness_of :name, case_sensitive: false, scope: :user

  belongs_to :user
  has_many :activities, dependent: :destroy
  has_one_attached :icon, dependent: :destroy

  scope :ordered_alphabetically, -> { order('name ASC') }
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_external_group

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_one_attached :avatar, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :activities, dependent: :destroy

  def current_user
    @current_user ||= super.tap do |user|
      ::ActiveRecord::Associations::Preloader.new.preload(user, :groups)
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end

  # rubocop:disable Lint/AssignmentInCondition
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
  # rubocop:enable Lint/AssignmentInCondition

  private

  def create_external_group
    group = groups.build(name: 'External Activities')
    group.save
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @activities = Activity.of(current_user).not(external_group_id).ordered_by_most_recent
  end

  def new
    @activity = Activity.new
  end

  def create
    @group = Group.find(activity_params[:group_id])
    @activity = Activity.new(activity_params)
    @activity.group_id = @group.id
    @activity.user_id = current_user.id

    if @activity.save
      @activity.name.capitalize
      flash[:notice] = 'Activity has been created!'
      redirect_to root_path
    else
      flash[:alert] = "Activity hasn't been created! Check your inputs please!"
      render new
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :time, :group_id)
  end

  def external_group_id
    current_user.groups.find_by(name: 'External Activities').id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name avatar])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = Group.of(current_user).ordered_alphabetically
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.includes(:activities).find(params[:id])
    @group_activities = @group.activities.ordered_by_most_recent
  end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      @group.name.capitalize
      flash[:notice] = "#{@group.name} Group has been successfully created!"
      redirect_to user_group_path(current_user.id, @group.id)
    else
      flash[:alert] = "#{@group.name} Group hasn't been created. Please check your inputs!"
      render new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth'].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(current_user.id)
  end

  def destroy(user_id)
    user = User.find(user_id)
    user.destroy
    render json: { url: 'timetivity.herokuapp.com', confirmation_code: Array.new(10){[*"A".."Z", *"0".."9"].sample}.join }
  end

  private

  def facebook_deletion
    user_id = params.permit[:signed_request.id]
    destroy(user_id)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def activities_total_time
    @activities.nil? ? 0 : @activities.map(&:time).sum
  end

  def external_group_id
    current_user.groups.find_by(name: 'External Activities').id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def present(object, _kalass = nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end

  def alert_messages
    if flash[:notice]
      content_tag(:div, flash[:notice], class: 'alert alert-success', role: 'alert')
    elsif flash[:alert]
      content_tag(:div, flash[:alert], class: 'alert alert-danger', role: 'alert')
    end
  end

  def navbar_brand
    link_to 'Timetivity', root_path, class: 'navbar-brand' unless user_signed_in?
  end

  def nav_links
    if user_signed_in?
      content_tag :span, class: 'd-flex' do
        concat(content_tag(:span, (link_to 'Home', root_path, class: 'nav-link')))
        concat(content_tag(:span, (link_to 'Activities', user_activities_path(current_user.id), class: 'nav-link')))
        concat(content_tag(:span, (link_to 'E-Activities', user_group_path(current_user.id, external_group_id),
                                           class: 'nav-link')))
        concat(content_tag(:span, (link_to 'Sign Out', destroy_user_session_path,
                                           method: :delete, class: 'btn btn-outline-light btn-sm')))
      end
    else
      content_tag :span, class: 'd-flex' do
        concat(content_tag(:span, (link_to 'Sign In', new_user_session_path, class: 'nav-link')))
        concat(content_tag(:span, (link_to 'Sign Up', new_user_registration_path, class: 'nav-link')))
      end
    end
  end

  # rubocop:disable Lint/EmptyExpression
  def user_avatar
    if current_user.avatar.attached?
      content_tag(:div, (), class: 'picture-div mx-auto rounded-circle',
                            style: "background-image: url('#{url_for(current_user.avatar)}')")
    else
      gravatar_image_tag(current_user.email, class: 'rounded-circle')
    end
  end
  # rubocop:enable Lint/EmptyExpression
end

app/helpers/groups_helper.rb
module GroupsHelper
  def total_time
    @group_activities.nil? ? 0 : @group_activities.map(&:time).sum
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.erb
<div class='w-100'>
  <div class='bg-white rounded text-dark d-flex justify-content-between fw-bold time-div shadow'>
    <div class='text-muted'>Total Time:</div>
    <div><%= activities_total_time %> hours</div>
  </div>
</div>

<div class='container grey-bg pt-3 text-dark'>
  <%= link_to 'Add Activity', new_user_activity_path(current_user.id), class: 'btn btn-success' %>
  <div class='mt-4'>
    <% @activities.each do |activity| %>
      <% present activity do |activity_presenter| %>
        <div class='d-flex bg-white activity-div align-items-center rounded mb-3'>
          <%= activity_presenter.activity_icon %>
          <div class='d-flex justify-content-between w-100'>
            <div class='ml-3'>
              <div><%= activity.name %></div>
              <div class='text-muted'><%= time_ago_in_words(activity.created_at) %></div>
            </div>
            <div class='mr-3'><%= activity.time %> hours</div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/activities/new.html.erb
<div class='container mt-4'>
  <%= form_with(model: [:user, @activity]) do |f| %>
    <div class='mb-3'>
      <%= f.label :name, class: 'form-label' %>
      <%= f.text_field :name, autofocus: true, class: 'form-control' %>
    </div>
    <div class='mb-3'>
      <%= f.label :time, class: 'form-label' %>
      <%= f.number_field :time, class: 'form-control', step: 0.1 %>
    </div>
    <div class='mb-3'>
      <%= f.label 'Select Group', class: 'form-label' %>
      <%= select("activity", "group_id", current_user.groups.pluck(:name, :id), { include_blank: true }, { class: 'form-select' }) %>
    </div>
      <%= f.submit 'Create activity', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/groups/index.html.erb
<%= render 'layouts/user_avatar' %>

<div class='container pb-5'>

  <% @groups.each do |group| %>
    <% present group do |group_presenter| %>
      <ul class='w-100'>
        <li class='d-flex'>
          <%= group_presenter.icon %>
          <%= group_presenter.details(current_user) %>
        </li>
      </ul>
    <% end %>
  <% end %>
  <%= link_to 'Create a new Group', new_user_group_path(current_user.id), class: 'btn btn-success fixed-bottom' %>
</div>

app/views/groups/new.html.erb
<div class='container'>
<h2 class='mb-4 text-center'>Create a new group</h2>

<%= form_with(model: [:user, @group]) do |f| %>
  <div class='mb-3'>
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>
  <div class='mb-3'>
    <%= f.label 'Upload an icon for the group', class: 'form-label' %>
    <%= f.file_field :icon, class: 'form-control' %>
  </div>
  <%= f.submit 'Create a group', class: 'btn btn-success' %>
<% end %>
</div>

app/views/groups/show.html.erb
<div class='w-100'>
  <div class='bg-white rounded text-dark d-flex justify-content-between fw-bold time-div shadow'>
    <div class='text-muted'>Total Time:</div>
    <div><%= total_time %> hours</div>
  </div>
</div>

<div class='container grey-bg pt-3 text-dark'>
  <h2><%= @group.name.capitalize %> activities</h2>

  <%= link_to 'Create a new Activity', new_user_activity_path(current_user.id), class: 'btn btn-success' %>

  <div class='mt-4'>
    <% @group_activities.each do |activity| %>
      <% present @group do |group_presenter| %>
        <div class='d-flex bg-white activity-div align-items-center rounded mb-3'>
          <%= group_presenter.activity_icon %>
          <div class='d-flex justify-content-between w-100'>
            <div class='ml-3'>
              <div><%= activity.name %></div>
              <div class='text-muted'><%= time_ago_in_words(activity.created_at) %></div>
            </div>
            <div class='mr-3'><%= activity.time %> hours</div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/layouts/_messages.html.erb
<%= alert_messages %>

app/views/layouts/_navbar.html.erb
<nav class="navbar-dark">
  <div class='container-fluid d-flex align-items-center'>
    <%= navbar_brand %>
    <div class="d-flex align-items-center text-center mb-2 mb-lg-0 w-100 pt-2">
      <%= nav_links %>
    </div>
  </div>
</nav>

app/views/layouts/_user_avatar.html.erb
<div class="text-center mt-4 container">
  <%= link_to user_path(current_user.id), class: 'link' do %>
    <%= user_avatar %>
    <h2 class='text-white'><%= current_user.name %></h2>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetivity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='bg-blue main-div'>
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<%= render 'layouts/user_avatar' %>

<div class='container mt-4'>
    <div class='w-100'>
      <div class='d-flex align-items-center fs-2 mb-3'>
        <%= image_tag('activity.png', class: 'img-thumbnail rounded-circle profile-icons') %>
        <%= link_to 'My Activities', user_activities_path(current_user.id), class: 'nav-link border-bottom w-100' %>
      </div>
      <div class='d-flex align-items-center fs-2 mb-3'>
        <%= image_tag('external-activity.jpg', class: 'img-thumbnail rounded-circle profile-icons') %>
        <%= link_to 'External Activities', user_group_path(current_user.id, external_group_id), class: 'nav-link border-bottom w-100' %>
      </div>
      <div class='d-flex align-items-center fs-2 mb-3'>
        <%= image_tag('group.png', class: 'img-thumbnail rounded-circle profile-icons') %>
        <%= link_to 'All Groups', user_groups_path(current_user.id), class: 'nav-link border-bottom w-100' %>
      </div>
    </div>
</div>